//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.4952
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamlDroidSample
{
	
	
	public partial class Resource
	{
		
		public partial class attr
		{
			
			private attr()
			{
			}
		}
		
		public partial class drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			private drawable()
			{
			}
		}
		
		public partial class id
		{
			
			// aapt resource value: 0x7f050000
			public const int myButton = 2131034112;
			
			private id()
			{
			}
		}
		
		public partial class layout
		{
			
			// aapt resource value: 0x7f030000
			public const int main = 2130903040;
			
			private layout()
			{
			}
		}
		
		public partial class @string
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			private @string()
			{
			}
		}
	}
}
